<?php

define('AFTER_REGISTRATION_SMS', 'AFTER_REGISTRATION_SMS');
define('AFTER_EXAM_SUBMISSION_SMS', 'AFTER_EXAM_SUBMISSION_SMS');
define('AFTER_ADMISSION_SMS', 'AFTER_ADMISSION_SMS');
define('AFTER_ADMISSION_CONFIRMATION_SMS', 'AFTER_ADMISSION_CONFIRMATION_SMS');


define('OTP_VERIFICATION_EMAIL', 'OTP_VERIFICATION_EMAIL');

define('AFTER_REGISTRATION_EMAIL', 'AFTER_REGISTRATION_EMAIL');
define('AFTER_EXAM_SUBMISSION_EMAIL', 'AFTER_EXAM_SUBMISSION_EMAIL');
define('AFTER_ADMISSION_EMAIL', 'AFTER_ADMISSION_EMAIL');
define('AFTER_ADMISSION_CONFIRMATION_EMAIL', 'AFTER_ADMISSION_CONFIRMATION_EMAIL');
define('PARTNER_PROGRESS_STALE_REMINDER_EMAIL', 'PARTNER_PROGRESS_STALE_REMINDER_EMAIL');


define('NOT_TO_REMOVE', [
    OTP_VERIFICATION_EMAIL,
    AFTER_REGISTRATION_SMS,
    AFTER_EXAM_SUBMISSION_SMS,
    AFTER_ADMISSION_SMS,
    AFTER_ADMISSION_CONFIRMATION_SMS,
    AFTER_REGISTRATION_EMAIL,
    AFTER_EXAM_SUBMISSION_EMAIL,
    AFTER_ADMISSION_EMAIL,
    AFTER_ADMISSION_CONFIRMATION_EMAIL,
    PARTNER_PROGRESS_STALE_REMINDER_EMAIL,
]);

define('COURSE_ATTENDANCE_VIEW', 'v_daily_course_attendance');
define('COURSE_SESSION_ATTENDANCE_VIEW', 'v_daily_course_session_attendance');
