steps:
  # - name: gcr.io/cloud-builders/gcloud
  #   id: copy-composer-auth
  #   entrypoint: 'bash'
  #   args: [ '-c', "gcloud secrets versions access latest --secret=COMPOSER_AUTH --format='get(payload.data)' | tr '_-' '/+' | base64 -d > backend/composerauth.json" ]
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_CONTAINER}:latest', '-f','Dockerfile', '.']
    id: 'build-backend-image'
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'api'
    args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_CONTAINER}:latest']
    id: 'push-backend-image'
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-backend-image'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_CONTAINER}:latest'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--port'
      - '8080'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    id: 'update-backend-traffic'
    args:
      - 'run'
      - 'services'
      - 'update-traffic'
      - '${_SERVICE_NAME}'
      - '--to-latest'
      - '--region'
      - 'europe-west1'     
images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_CONTAINER}:latest'
substitutions:
    _REPO_NAME: omcp-repo # default value
    _CONTAINER: backend # default value  
    _SERVICE_NAME: omcp-backend # default value  
options:
  logging: CLOUD_LOGGING_ONLY