<?php

define('AFTER_REGISTRATION_SMS', 'AFTER_REGISTRATION_SMS');
define('AFTER_EXAM_SUBMISSION_SMS', 'AFTER_EXAM_SUBMISSION_SMS');
define('AFTER_ADMISSION_SMS', 'AFTER_ADMISSION_SMS');
define('AFTER_ADMISSION_CONFIRMATION_SMS', 'AFTER_ADMISSION_CONFIRMATION_SMS');


define('AFTER_REGISTRATION_EMAIL', 'AFTER_REGISTRATION_EMAIL');
define('AFTER_EXAM_SUBMISSION_EMAIL', 'AFTER_EXAM_SUBMISSION_EMAIL');
define('AFTER_ADMISSION_EMAIL', 'AFTER_ADMISSION_EMAIL');
define('AFTER_ADMISSION_CONFIRMATION_EMAIL', 'AFTER_ADMISSION_CONFIRMATION_EMAIL');


define('NOT_TO_REMOVE', [
    AFTER_REGISTRATION_SMS,
    AFTER_EXAM_SUBMISSION_SMS,
    AFTER_ADMISSION_SMS,
    AFTER_ADMISSION_CONFIRMATION_SMS,
    AFTER_REGISTRATION_EMAIL,
    AFTER_EXAM_SUBMISSION_EMAIL,
    AFTER_ADMISSION_EMAIL,
    AFTER_ADMISSION_CONFIRMATION_EMAIL,
]);
